<?php
require(VIEWS_PATH . 'includes/header.phtml');
?>

<div class="container">
    <div class="col-md-12">
        <h1>Cadastrar nova despesa</h1>
        <hr>
    </div>
    <div class="col-md-12">
        <form method="POST" action="<?= HOME; ?>/posts/edit/<?= $this->post['id']; ?>">
            <div class="form-group">
                <label for="exampleInputEmail1">Titulo</label>
                <input type="text" class="form-control" name="title" value="<?= $this->post['title']; ?>">
            </div>

            <div class="form-group">
                <label for="exampleInputEmail1">Descrição</label>
                <input type="text" class="form-control" name="description" value="<?= $this->post['description']; ?>">
            </div>

            <div class="form-group">
                <label for="exampleInputPassword1">Conteúdo</label>
                <textarea name="content" id="" cols="30" rows="10" class="form-control"><?= $this->post['content']; ?></textarea>
            </div>

            <div class="form-group">
                <label for="exampleInputEmail1">Slug</label>
                <input type="text" class="form-control" name="slug" value="<?= $this->post['slug']; ?>">
            </div>

            <div class="form-group">
                <label for="exampleInputEmail1">Tipo</label>
                <select name="type">
                    <option value="#">Selecione o tipo do conteúdo</option>
                    <option value="post" <?php if ($this->post['type'] == 'post') : ?> selected <?php endif ?>>Post</option>
                    <option value="page" <?php if ($this->post['type'] == 'page') : ?> selected <?php endif ?>>Página</option>
                </select>
            </div>

            <div class="form-group">
                <label for="exampleInputEmail1">Tipo</label>
                <select name="user_id">
                    <option value="#">Selecione o autor</option>
                    <?php foreach ($this->users as $u) : ?>
                        <option value="<?= $u['id']; ?>" <?php if ($this->post['user_id'] == $u['id']) : ?> selected <?php endif ?>>
                            <?= $u['first_name'] . ' ' . $u['last_name']; ?>
                        </option>
                    <?php endforeach; ?>
                </select>
            </div>

            <button type="submit" class="btn btn-success btn-lg pull-right">Salvar Post</button>
        </form>
    </div>
</div>

<?php
require(VIEWS_PATH . 'includes/footer.phtml');
?>