<?php
require(VIEWS_PATH . 'includes/header.phtml');
?>

<div class="container">
    <div class="col-md-12">
        <?php require VIEWS_PATH . 'includes/messages.phtml'; ?>
    </div>

    <div class="col-md-12">
        <h1>Usuários - <small>Cadastrar novo usuários</small></h1>
        <hr>
    </div>
    <div class="col-md-12">
        <form method="POST" action="<?= HOME; ?>/users/new">
            <div class="form-group">
                <label for="exampleInputEmail1">Nome</label>
                <input type="text" class="form-control" name="first_name">
            </div>

            <div class="form-group">
                <label for="exampleInputEmail1">Sobrenome</label>
                <input type="text" class="form-control" name="last_name">
            </div>

            <div class="form-group">
                <label for="exampleInputEmail1">Username</label>
                <input type="text" class="form-control" name="username">
            </div>

            <div class="form-group">
                <label for="exampleInputEmail1">Senha</label>
                <input type="password" class="form-control" name="password">
            </div>

            <div class="form-group">
                <label for="exampleInputEmail1">Confirmar Senha</label>
                <input type="password" class="form-control" name="password_confirm">
            </div>

            <button type="submit" class="btn btn-success btn-lg pull-right">Salvar Usuários</button>
        </form>
    </div>
</div>

<?php
require(VIEWS_PATH . 'includes/footer.phtml');
?>